Dev: Testing CI/CD Prod Phase

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -57,12 +57,24 @@ jobs:
         run: |
           git config user.email "lloydsibson@gmail.com"
           git config user.name "Lloyd Sibson"
-      - name: Merge Development to Production
+      - name: Merge branch to production
+        id: merge
         run: |
-          git checkout master
-          git pull origin master
-          git merge ${{ github.ref }} --no-ff --allow-unrelated-histories
-          git push origin master
+          git checkout production
+          git pull origin production
+          git merge ${{ github.ref }} --no-ff --allow-unrelated-histories || echo "Merge conflict detected" > conflict.txt
+
+      - name: Check for merge conflicts
+        run: |
+          if [ -f conflict.txt ]; then
+            echo "Merge conflict detected. Manual resolution required."
+             exit 1
+          fi
+
+      - name: Push changes
+        if: success()
+        run: |
+          git push origin production
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
