Dev: Testing CI/CD Prod Phase

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -59,26 +59,34 @@ jobs:
           git config user.name "Lloyd Sibson"
       - name: Fetch all branches
         run: git fetch --all
-      - name: Merge branch to production
-        id: merge
-        run: |
-          git checkout production
-          git pull origin production
-          git merge ${{ github.ref }} --no-ff --allow-unrelated-histories || echo "Merge conflict detected" > conflict.txt
 
-      - name: Check for merge conflicts
-        run: |
-          if [ -f conflict.txt ]; then
-            echo "Merge conflict detected. Manual resolution required."
-             exit 1
-          fi
+      - name: Merge Dev -> Prod
+        uses: devmasx/merge-branch@master
+        with:
+          type: now
+          target_branch: production
+          message: Merge development into production
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Merge branch to production
+      #   id: merge
+      #   run: |
+      #     git checkout production
+      #     git pull origin production
+      #     git merge ${{ github.ref }} --no-ff --allow-unrelated-histories || echo "Merge conflict detected" > conflict.txt
 
-      - name: Push changes
-        if: success()
-        run: |
-          git push origin production
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Check for merge conflicts
+      #   run: |
+      #     if [ -f conflict.txt ]; then
+      #       echo "Merge conflict detected. Manual resolution required."
+      #        exit 1
+      #     fi
+
+      # - name: Push changes
+      #   if: success()
+      #   run: |
+      #     git push origin production
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   Deploy-Production:
     needs: Merge-Dev-to-Prod
